#!/usr/bin/env python3 
import sys
import subprocess
import os

command = sys.argv[1] if len(sys.argv) > 1 else None

script_directory = os.path.dirname(os.path.realpath(__file__))
if command == "init":
    sys.exit(subprocess.run([sys.executable, os.path.join(script_directory, "init.py")] + sys.argv[1:]).returncode)

elif command == "commit":
    sys.exit(subprocess.run([sys.executable, os.path.join(script_directory, "commit.py")] + sys.argv[1:]).returncode)

elif command == "open":
    sys.exit(subprocess.run([sys.executable, os.path.join(script_directory, "open.py")] + sys.argv[1:]).returncode)

elif command == "log":
    sys.exit(subprocess.run([sys.executable, os.path.join(script_directory, "log.py")] + sys.argv[1:]).returncode)
    
else: 
    print(f"Unknown command: {command}")
    print("Invalid command. Please use 'init', 'commit', 'open', or 'log', along with required arguments.")
    sys.exit(1)

# If on MacOS / Linux, move this file, commit.py, init.py, open.py, and log.py to /usr/local/bin and make it executable with `chmod +x sccs`