#!/usr/bin/env python3 
import sys
import subprocess

command = sys.argv[1] if len(sys.argv) > 1 else None

if command == "init":
    sys.exit(subprocess.run(["python3", "init.py"] + sys.argv[1:]).returncode)

elif command == "commit":
    sys.exit(subprocess.run(["python3", "commit.py"] + sys.argv[1:]).returncode)

else: 
    print(f"Unknown command: {command}")
    print("Invalid command. Please use either 'init' or 'commit', along with required arguments.")
    sys.exit(1)

# If on MacOS / Linux, move this file to /usr/local/bin and make it executable with `chmod +x sccs`