#!/usr/bin/env python3 
import sys
import subprocess
import os

COMMANDS = ["init", "commit", "open", "log", "diff", "status", "help", "branch", "switch"]

command = sys.argv[1] if len(sys.argv) > 1 else None

script_directory = os.path.dirname(os.path.realpath(__file__))

for c in COMMANDS:
    if command == c:
        sys.exit(subprocess.run([sys.executable, os.path.join(script_directory, f"{c}.py")] + sys.argv[1:]).returncode)

    else: 
        print(f"Unknown command: {command}")
        print("Invalid command. Please use 'init', 'commit', 'open', 'log', 'diff', 'status', 'help', 'branch', or 'switch', along with required arguments.")
        print("For help, use the 'sccs help' command.")
        sys.exit(1)
        break

# If on MacOS / Linux, move this file, commit.py, init.py, open.py, log.py, diff.py, status.py, help.py, branch.py , and switch.py to /usr/local/bin and make it executable with `chmod +x /usr/local/bin/sccs`
