#!/usr/bin/env python3 
"""SCCS - Simple Contract Control System; CLI tunnel to point to chosen command"""

import subprocess
import sys
from pathlib import Path

import exceptions

COMMANDS = [
    "init",
    "commit",
    "open",
    "log",
    "diff",
    "status",
    "help",
    "branch",
    "switch",
    "publish",
    "clone",
    "origin"
]


def get_entered_command() -> str | None:
    return sys.argv[1] if len(sys.argv) > 1 else None


def get_script_directory() -> Path:
    return Path(__file__).parent.resolve()


def run_command(command: str, script_directory: Path) -> None:
    sys.exit(
        subprocess.run([
            sys.executable,
            script_directory / f"{command}.py"]
             + sys.argv[1:]
        ).returncode
    )


def execute_command(command: str, script_directory: Path, COMMANDS: list) -> None:
    if command not in COMMANDS:
        raise exceptions.UnknownCommandError(
            f"Unknown command: {command}. Please use 'init', 'commit', 'open', 'log', "
            f"'diff', 'status', 'help', 'branch', 'switch', or 'publish', along with required "
            f"arguments. For help, use the 'sccs help' command."
        )
    run_command(command, script_directory)


def main() -> None:
    command = get_entered_command()

    script_directory = get_script_directory()

    execute_command(command, script_directory, COMMANDS)


if __name__ == "__main__":
    try:
        main()

    except exceptions.SCCSException as e:
        print(f"An error occurred:\n{e}\n")
        sys.exit(1)

    except Exception as e:
        print(f"An unexpected error occurred:\n\n{type(e).__name__}: {e}\n")
        sys.exit(2)
else:
    raise exceptions.FileImportedAsModuleError(
        "This file cannot be run as a module. Please run it as a script."
    )

# If on MacOS / Linux, move this file, commit.py, init.py, open.py, log.py, diff.py,
# status.py, help.py, branch.py , and switch.py to /usr/local/bin and make it executable
#  with `chmod +x /usr/local/bin/sccs`.
