#!/usr/bin/env python3 
import os
import subprocess
import sys

import exceptions

COMMANDS = [
    "init",
    "commit",
    "open",
    "log",
    "diff",
    "status",
    "help",
    "branch",
    "switch"
]


def get_entered_command():
    return sys.argv[1] if len(sys.argv) > 1 else None


def get_script_directory():
    return os.path.dirname(os.path.realpath(__file__))


def run_command(command, script_directory):
    sys.exit(
        subprocess.run([
            sys.executable,
            os.path.join(script_directory, f"{command}.py")]
             + sys.argv[1:]
        ).returncode
    )


def execute_command(command, script_directory, COMMANDS):
    if command not in COMMANDS:
        raise exceptions.UnknownCommandError(f"Unknown command: {command}. Please use 'init', 'commit', 'open', 'log', 'diff', 'status', 'help', 'branch', or 'switch', along with required arguments. For help, use the 'sccs help' command.")
    run_command(command, script_directory)


if __name__ == "__main__":

    command = get_entered_command()

    script_directory = get_script_directory()
    
    execute_command(command, script_directory, COMMANDS)

# If on MacOS / Linux, move this file, commit.py, init.py, open.py, log.py, diff.py,
# status.py, help.py, branch.py , and switch.py to /usr/local/bin and make it executable
#  with `chmod +x /usr/local/bin/sccs`.
