name: Format

on:
  pull_request:
    branches: [main]
    paths:
      - "**.py"

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install formatters
        run: pip install black isort

      - name: Run isort
        run: isort --profile black .

      - name: Run black
        run: black .

      - name: Commit changes
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format with black + isort"
  

